version: 1.3.1.{build}
skip_tags: true
max_jobs: 1
configuration: Release
platform: x86
clone_depth: 50
image: Visual Studio 2017
before_build:
- cmd: git clone "https://github.com/HearthSim/HearthDb" "HearthDb"
- cmd: nuget restore
build:
  project: Graveyard.sln
  verbosity: minimal
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '$(appveyor_build_version)'
artifacts:
  - path: %APPVEYOR_BUILD_FOLDER%\Graveyard\bin\x86\Release\Graveyard.dll
    name: Graveyard
